### ISSUE TITLE
tests not working

### ISSUE THREAD

**Issue by kqee** [iamatulsingh/pinscrape#15]
whenever attempting to run `e2e.py` in the `tests/` directory, an import error is raised. 

```
Traceback (most recent call last):
  File "C:\path\to\project\pinscrape\tests\e2e.py", line 1, in <module>
    from pinscrape import scraper
ModuleNotFoundError: No module named 'pinscrape'
```

**Comment by iamatulsingh** [comment]
Do you already have it installed? You can change the code and install it using `pip install .`

**Comment by kqee** [comment]
yes i have it installed, i forked it and cloned it. Anyway, I have entered that command but was greeted with an error.

```
error: subprocess-exited-with-error

  Ã— Getting requirements to build wheel did not run successfully.
  â”‚ exit code: 1
  â•°â”€> [24 lines of output]
      Traceback (most recent call last):
        File "c:\Users\$USER\code\pinscrape\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "c:\Users\$USER\code\pinscrape\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "c:\Users\$USER\code\pinscrape\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\$USER\AppData\Local\Temp\pip-build-env-o8mf_2_l\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel 
          return self._get_build_requires(config_settings, requirements=['wheel']) 
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
        File "C:\Users\$USER\AppData\Local\Temp\pip-build-env-o8mf_2_l\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "C:\Users\$USER\AppData\Local\Temp\pip-build-env-o8mf_2_l\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\$USER\AppData\Local\Temp\pip-build-env-o8mf_2_l\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 2, in <module>
        File "C:\Users\$USER\code\pinscrape\pinscrape\__init__.py", line 2, in <module>
          from .pinscrape import scraper
        File "C:\Users\$USER\code\pinscrape\pinscrape\pinscrape.py", line 4, in <module>
          import cv2
      ModuleNotFoundError: No module named 'cv2'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Ã— Getting requirements to build wheel did not run successfully.
â”‚ exit code: 1
â•°â”€> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
sorry about the messed up texts.

this is likely Windows' 11 issue, I will attempt to fix this and get back here ASAP.

**Comment by kqee** [comment]
had a realisation i was doing something dumb, resolved. sorry.
